"""Graph data models shared across ingestion and retrieval."""

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class Entity:
    """A named entity extracted from document text.

    Attributes:
        name: Lowercased entity name (used as the graph node key).
        entity_type: Category label (e.g. "person", "organization").
        description: Comprehensive description merged from all source chunks.
        document_ids: IDs of the chunks this entity was found in.
    """

    name: str
    entity_type: str = ""
    description: str = ""
    document_ids: List[str] = field(default_factory=list)


@dataclass
class Relationship:
    """A directed relationship between two entities.

    Attributes:
        source: Name of the source entity (lowercased).
        target: Name of the target entity (lowercased).
        relation: Short label for the relationship type (e.g. "founded").
        description: Full explanation of the connection.
        weight: Strength of the relationship, 1–10.
        document_ids: IDs of the chunks this relationship was found in.
    """

    source: str
    target: str
    relation: str
    description: str = ""
    weight: float = 1.0
    document_ids: List[str] = field(default_factory=list)


@dataclass
class Community:
    """A cluster of related entities detected via community detection.

    Attributes:
        id: Unique UUID for this community.
        level: Hierarchy level — 0 is the coarsest, higher values are finer.
        entities: List of entity names belonging to this community.
        title: Short topic label generated by the LLM.
        summary: 1-2 sentence overview generated by the LLM.
        full_content: Markdown report with findings, generated by the LLM.
        findings: Structured list of {"explanation", "data_refs"} bullets.
        rank: Importance score 1–10 assigned by the LLM.
        embedding: Embedding of the summary for semantic scoring at query time.
    """

    id: str
    level: int
    entities: List[str]
    title: str = ""
    summary: str = ""
    full_content: str = ""
    findings: List[Dict[str, str]] = field(default_factory=list)
    rank: float = 0.0
    embedding: Optional[List[float]] = field(default=None, repr=False)
